# Generated by Django 3.0.4 on 2020-03-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20200321_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='address x', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='city x', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default='zip code x', max_length=10),
        ),
    ]
