# Generated by Django 3.0.4 on 2020-03-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20200322_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='radius',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
